name: Badges

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ '8.1' ]
        wp_version: [ '6.4' ]

    name: WordPress ^${{ matrix.wp_version }} - PHP ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: pcov

      - name: Install PHP dependencies
        run: composer update --prefer-stable --no-interaction --no-progress --ansi

      - name: Setup WordPress
        run: composer run-script setup:wp:${{ matrix.wp_version }}

      - name: Code coverage
        run: composer run-script test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          directory: tests/coverage
          files: tests/coverage/clover.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
